name: project
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  provider: ^6.1.2
  data_table_2: ^2.5.12
  freezed_annotation: ^2.4.1
  mine:
    git:
      url: https://github.com/fazil-kp/mine.git
      ref: main
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.9
  hive_flutter: ^1.1.0
  auto_binding_field: ^0.0.7
  dropdown_search: ^5.0.6
  syncfusion_flutter_datepicker: ^27.1.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

